syntax = "proto3";
//package helloworld;
option go_package = ".;proto";
import "base.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/Timestamp.proto";
service Greeter {
    //rpc SayHello (HelloReply) returns (HelloRequest);
    rpc SayHello (HelloRequest) returns (HelloReply);
    rpc Ping(google.protobuf.Empty) returns (Pong);
}
message HelloReply {
    string name =1;
}
enum Gender {
    MALE =0;
    FEMALE=1;
}
message HelloRequest {
    string name =1;
    string url=2;
    // message Result {
    //     string url =1;
    //     string name =2;
    // }
    // repeated Result data=2;
    Gender g = 3;
    map<string ,string> mp = 4;
    google.protobuf.Timestamp addTime=5;
}

